services:
  - type: web
    name: your-app-name
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /shopping/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html